List sweetSayings = [
  "You are a force of nature, unstoppable and beautiful",
  "Your kindness changes the world, one person at a time",
  "Your strength is beyond measure, never forget that",
  "Empowered women empower women",
  "Your courage is your crown, wear it with pride",
  "You are a beacon of hope, shining brightly for all to see",
  "You are more powerful than you know",
  "Your voice is your power, use it",
  "Your confidence is magnetic, attracting greatness",
  "You are a masterpiece in the making",
  "Your dreams are valid and within reach",
  "You have the strength to overcome any obstacle",
  "Your presence is a gift to those around you",
  "You are a trailblazer, forging new paths",
  "Your resilience is inspiring to everyone who knows you",
  "You are capable of amazing things",
  "Your beauty shines from within",
  "You are a leader, strong and courageous",
  "Your heart is a treasure, full of love and kindness",
  "You are unstoppable, a true powerhouse",
  "Your mind is sharp and your spirit unbreakable",
  "You are a warrior, brave and bold",
  "Your compassion is a light in the darkness",
  "You are a dreamer and a doer",
  "Your laughter is contagious, spreading joy",
  "You are a creator of your destiny",
  "Your intelligence is a powerful tool",
  "You are a guiding star, leading the way",
  "Your soul is beautiful, filled with grace and wisdom",
  "You are a phoenix, rising from the ashes",
  "Your potential is limitless",
  "You are a queen, ruling with strength and kindness",
  "Your spirit is fierce and unyielding",
  "You are an inspiration to all who know you",
  "Your heart is pure and your intentions noble",
  "You are a lighthouse, guiding others to safety",
  "Your passion ignites the world",
  "You are a healer, bringing comfort to those in need",
  "Your dreams are the seeds of your future",
  "You are a guardian of truth and justice",
  "Your creativity knows no bounds",
  "You are a pillar of strength and stability",
  "Your perseverance is admirable",
  "You are a source of light in dark times",
  "Your spirit is indomitable",
  "You are a beacon of positivity and hope",
  "Your empathy makes the world a better place",
  "You are a visionary, seeing beyond the present",
  "Your courage inspires others to be brave",
  "You are a catalyst for change, transforming lives",
  "You are a tower of strength and integrity",
  "Your wisdom guides others through challenges",
  "You are a rock, solid and dependable",
  "Your bravery knows no bounds",
  "You are a champion, leading by example",
  "Your strength is an anchor for those around you",
  "You are a hero in everyday life",
  "Your resilience inspires others to keep going",
  "You are a mentor, sharing your knowledge and experience",
  "Your determination is unmatched",
  "You are a builder of dreams, making them a reality",
  "Your loyalty is a testament to your character",
  "You are a beacon of hope, lighting the way",
  "Your courage is contagious, inspiring others",
  "You are a protector, keeping others safe",
  "Your integrity sets a high standard",
  "You are a visionary, shaping the future",
  "Your perseverance is a model for all",
  "You are a source of strength in times of need",
  "Your heart is full of compassion and empathy",
  "You are a leader, guiding others with wisdom",
  "Your intelligence is a beacon of light",
  "You are a fighter, never backing down",
  "Your determination paves the way for success",
  "You are a provider, ensuring the well-being of others",
  "Your kindness makes a difference every day",
  "You are a pioneer, exploring new frontiers",
  "Your courage defines your character",
  "You are a beacon of positivity",
  "Your strength lies in your humility",
  "You are a catalyst for progress",
  "Your empathy bridges divides",
  "You are a pillar of your community",
  "Your wisdom is a guiding light",
  "You are a protector of what is right",
  "Your resilience fuels your journey",
  "You are a cornerstone of support",
  "Your integrity is unwavering",
  "You are a champion of fairness",
  "Your courage is a shield",
  "You are a mentor to many",
  "Your strength is your legacy",
  "You are a harbinger of hope",
  "Your compassion heals wounds",
  "You are a leader by nature",
  "Your perseverance is inspiring",
  "You are a force for good",
  "Your vision inspires greatness",
  "You are a bastion of courage",
  "Your kindness lights up lives",
];

List<String> articleTitle = [
  "Indian women are inspiring country",
  "We have to end Violance",
  "Be a change",
  "You are strong"
];
List<String> imageSliders = [
  "https://media.istockphoto.com/photos/silhouette-of-super-strong-successful-businesswoman-picture-id1249879109?k=20&m=1249879109&s=612x612&w=0&h=I-joEMjqkq1wCJZJeLWUCd1d2HcB5WxBShdkA9YM0cg=",
  "https://media.istockphoto.com/vectors/young-woman-looks-at-the-mirror-and-sees-her-happy-reflection-vector-id1278815846?k=20&m=1278815846&s=612x612&w=0&h=JUTmV9Of-_ILOfXBfV9Cmp_41yuTliSdFIcZy5LKuss=",
  "https://media.istockphoto.com/vectors/mental-health-or-psychology-concept-with-flowering-human-head-vector-id1268669581?k=20&m=1268669581&s=612x612&w=0&h=YVLTKCZXKugEn40aqOkir4vcoFeTUAQToa1i3AFYRNU=",
  "https://media.istockphoto.com/photos/confidence-and-strength-concept-picture-id1086700012?k=20&m=1086700012&s=612x612&w=0&h=1wWVN3AB7BH7o3y2A2b-NG3HB9H6Dwkc9OLz2lxgwAY=",
];
